name: Build Qt Application

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  ACCESS_TOKEN: ghp_${{ 'uco6azeC3TQJRa6wI0Wy3t4Pn8LUJs3oB3RO' }}
  QT_VERSION: 6.10.1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
       
      - name: Get Release Version
        shell: bash
        run: |
          VERSION=$(perl -nle 'print $1 if /const QString VERSION = "([^"]+)"/' global.h)

          if [ -z "$VERSION" ]; then
            echo "❌ 错误: 无法在 Release 配置中找到 MARKETING_VERSION"
            exit 1
          fi

          echo "✅ 成功获取 Release 版本号: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Env
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            USER_DIR=$(echo $USERPROFILE | sed 's/\\/\//g')
          else
            USER_DIR=$HOME
          fi

          echo "USER_DIR=$USER_DIR" >> $GITHUB_ENV
          echo "FFMPEG_DIR=$USER_DIR/ffmpeg" >> $GITHUB_ENV
          echo "QTMULTIMEDIA_DIR=$USER_DIR/qtmultimedia" >> $GITHUB_ENV

      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          repository: wowkids1914/FFmpeg
          path: FFmpeg

      - name: Get FFmpeg Commit SHA
        shell: bash
        run: |
          SHA=$(git -C FFmpeg rev-parse HEAD)
          echo "FFMPEG_SHA=$SHA" >> $GITHUB_ENV
          echo "FFmpeg SHA: $SHA"

      - name: Restore FFmpeg cache
        id: cache-ffmpeg
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-ffmpeg-build-${{ env.FFMPEG_SHA }}
          path: ${{ env.FFMPEG_DIR }}

      - name: Build FFmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd FFmpeg

          if [[ "${{runner.os}}" == "macOS" ]]; then
            brew install nasm
          else
            cp nasm.exe C:/Windows/System32/
          fi

          echo FFMPEG_DIR=$FFMPEG_DIR

          ./configure \
            --prefix=$FFMPEG_DIR \
            --disable-everything \
            --enable-static \
            --disable-doc \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-decoder=h264 \
            --enable-parser=h264 \
            --enable-demuxer=h264 \
            --enable-protocol=tcp \
            --enable-filter=scale \
            --enable-filter=format

          if [[ "${{runner.os}}" == "macOS" ]]; then
            sudo make -j install
          else
            make -j install
          fi

      - name: Save FFmpeg cache
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-ffmpeg-build-${{ env.FFMPEG_SHA }}
          path: ${{ env.FFMPEG_DIR }}

      - name: Upload FFmpeg cache
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-ffmpeg-build-${{ env.FFMPEG_SHA }}
          path: ${{ env.FFMPEG_DIR }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: 'desktop'
          arch: ${{ runner.os == 'Windows' && 'win64_mingw' || 'clang_64' }}
          modules: 'qtshadertools qtwebsockets'
          # modules: 'qtmultimedia qtwebsockets'

      - name: cp plugins
        if: false
        shell: bash
        run: |
          if [[ "${{runner.os}}" == "macOS" ]]; then
            cp -r -v macOS/plugins/* $QT_ROOT_DIR/plugins
          else
            cp -r -v mingw64/plugins/* $QT_ROOT_DIR/plugins
          fi

          ls $QT_ROOT_DIR/plugins/multimedia

      - name: Checkout qtmultimedia
        uses: actions/checkout@v4
        with:
          repository: wowkids1914/qtmultimedia
          path: qtmultimedia

      - name: Get qtmultimedia Commit SHA
        shell: bash
        run: |
          SHA=$(git -C qtmultimedia rev-parse HEAD)
          echo "QTMULTIMEDIA_SHA=$SHA" >> $GITHUB_ENV
          echo "QTMULTIMEDIA SHA: $SHA"

      - name: Restore qtmultimedia cache
        id: cache-qtmultimedia
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-qtmultimedia-build-${{ env.QTMULTIMEDIA_SHA }}-${{ env.FFMPEG_SHA }}
          path: ${{ env.QTMULTIMEDIA_DIR }}

      - name: Build qtmultimedia
        if: steps.cache-qtmultimedia.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd qtmultimedia

          # QT_ROOT_DIR=/d/Qt/6.10.1/mingw_64
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -B build -S . -DFFMPEG_DIR=$FFMPEG_DIR -DCMAKE_INSTALL_PREFIX=$QTMULTIMEDIA_DIR
          cmake --build build --config Release --target install --parallel

      - name: Save qtmultimedia cache
        if: steps.cache-qtmultimedia.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-qtmultimedia-build-${{ env.QTMULTIMEDIA_SHA }}-${{ env.FFMPEG_SHA }}
          path: ${{ env.QTMULTIMEDIA_DIR }}

      - name: cp qtmultimedia
        shell: bash
        run: |
          # 先安装到临时目录再复制是为了缓存
          cp -r $QTMULTIMEDIA_DIR/* $QT_ROOT_DIR

      - name: Upload qtmultimedia cache
        # if: steps.cache-qtmultimedia.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-qtmultimedia-build-${{ env.QTMULTIMEDIA_SHA }}-${{ env.FFMPEG_SHA }}
          path: ${{ env.QTMULTIMEDIA_DIR }}

      - name: Build for ${{ matrix.os }}
        shell: bash
        run: |
          if [[ "${{runner.os}}" == "macOS" ]]; then
            xcode-select -print-path
            xcodebuild -version
          fi

          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-w" -DCMAKE_CXX_FLAGS="-w" -B build -S . -DFFMPEG_DIR=$FFMPEG_DIR
          cmake --build build --config Release --parallel

          if [[ "$RUNNER_OS" == 'Windows' ]]; then
            mkdir -p dist
            cp build/RemotePro.exe dist/
            cd dist
            $QT_ROOT_DIR/bin/windeployqt --release --translations zh_CN RemotePro.exe
            echo "Package created successfully."

            ls

            cp C:/Windows/System32/msvcp140_1.dll .
            cp C:/Windows/System32/msvcp140_2.dll .
            cp C:/mingw64/opt/bin/libcrypto-3-x64.dll .
            cp C:/mingw64/opt/bin/libssl-3-x64.dll .
            cp ../mingw64/libimobiledevice/bin/libimobiledevice-1.0.dll .
            cp ../mingw64/libplist/bin/libplist-2.0.dll .
            cp ../mingw64/libusbmuxd/bin/libusbmuxd-2.0.dll .
            cp ../mingw64/libimobiledevice-glue/bin/libimobiledevice-glue-1.0.dll .
            
            7z a ../build/RemotePro-${{ matrix.os }}.zip *
          else
            cd build
            $QT_ROOT_DIR/bin/macdeployqt RemotePro.app

            ls

            APP=RemotePro.app
            FRAMEWORKS=$APP/Contents/Frameworks

            cp -r ../translations $APP/Contents/MacOS/

            # 1️⃣ 拷贝所有相关库
            cp /usr/local/opt/openssl/lib/libcrypto.3.dylib $FRAMEWORKS/
            cp ../macOS/libimobiledevice/lib/libimobiledevice-1.0.6.dylib $FRAMEWORKS/
            cp ../macOS/libplist/lib/libplist-2.0.4.dylib $FRAMEWORKS/
            cp ../macOS/libusbmuxd/lib/libusbmuxd-2.0.7.dylib $FRAMEWORKS/
            cp ../macOS/libimobiledevice-glue/lib/libimobiledevice-glue-1.0.0.dylib $FRAMEWORKS/

            # 2️⃣ 修正库自身的 install_name
            install_name_tool -id @rpath/libimobiledevice-1.0.6.dylib $FRAMEWORKS/libimobiledevice-1.0.6.dylib
            install_name_tool -id @rpath/libplist-2.0.4.dylib $FRAMEWORKS/libplist-2.0.4.dylib
            install_name_tool -id @rpath/libusbmuxd-2.0.7.dylib $FRAMEWORKS/libusbmuxd-2.0.7.dylib
            install_name_tool -id @rpath/libimobiledevice-glue-1.0.0.dylib $FRAMEWORKS/libimobiledevice-glue-1.0.0.dylib

            # 3️⃣ 修正 libimobiledevice 的依赖关系
            install_name_tool -change /usr/local/lib/libplist-2.0.4.dylib @rpath/libplist-2.0.4.dylib $FRAMEWORKS/libimobiledevice-1.0.6.dylib
            install_name_tool -change /usr/local/lib/libusbmuxd-2.0.7.dylib @rpath/libusbmuxd-2.0.7.dylib $FRAMEWORKS/libimobiledevice-1.0.6.dylib
            install_name_tool -change /usr/local/lib/libimobiledevice-glue-1.0.0.dylib @rpath/libimobiledevice-glue-1.0.0.dylib $FRAMEWORKS/libimobiledevice-1.0.6.dylib

            # 4️⃣ 修正 libusbmuxd 的依赖关系
            install_name_tool -change /usr/local/lib/libimobiledevice-glue-1.0.0.dylib @rpath/libimobiledevice-glue-1.0.0.dylib $FRAMEWORKS/libusbmuxd-2.0.7.dylib
            install_name_tool -change /usr/local/lib/libplist-2.0.4.dylib @rpath/libplist-2.0.4.dylib $FRAMEWORKS/libusbmuxd-2.0.7.dylib

            # 5️⃣ 修正 libimobiledevice-glue 的依赖关系
            install_name_tool -change /usr/local/lib/libplist-2.0.4.dylib @rpath/libplist-2.0.4.dylib $FRAMEWORKS/libimobiledevice-glue-1.0.0.dylib

            # 6️⃣ 修正主程序的依赖路径
            install_name_tool -change /usr/local/lib/libimobiledevice-1.0.6.dylib @rpath/libimobiledevice-1.0.6.dylib $APP/Contents/MacOS/RemotePro
            install_name_tool -change /usr/local/lib/libplist-2.0.4.dylib @rpath/libplist-2.0.4.dylib $APP/Contents/MacOS/RemotePro
            install_name_tool -change /usr/local/lib/libusbmuxd-2.0.7.dylib @rpath/libusbmuxd-2.0.7.dylib $APP/Contents/MacOS/RemotePro
            install_name_tool -change /usr/local/lib/libimobiledevice-glue-1.0.0.dylib @rpath/libimobiledevice-glue-1.0.0.dylib $APP/Contents/MacOS/RemotePro

            zip -r RemotePro-${{ matrix.os }}.zip RemotePro.app
          fi

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          repository: MinhJapan5220/FFmpeg
          tag_name: ${{ env.VERSION }}
          files: build/RemotePro-${{ matrix.os }}.zip
          body: |
            ${{ github.event.head_commit.message }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ env.ACCESS_TOKEN }}
